### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [hustvl/LKCell#2]
Hi,

Niels here from the open-source team at Hugging Face. Congrats on your work! I discovered your work through the paper page: https://huggingface.co/papers/2407.18054 (feel free to claim the paper so that it appears at your HF account!).

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

## Upload checkpoints in seperate model repos, make sure download stats work

I see the models are already on the hub which is great, however we recommend pushing checkpoints to individual model repos so that download stats work.

Here's a guide: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub. The PyTorchModelHubMixin is suited for custom PyTorch models, as is the case here.

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by xiazhi1** [comment]
> Hi,
> 
> Niels here from the open-source team at Hugging Face. Congrats on your work! I discovered your work through the paper page: https://huggingface.co/papers/2407.18054 (feel free to claim the paper so that it appears at your HF account!).
> 
> However there are a couple of things which could improve the discoverability of your work, which I've listed below.然而，有一些事情可以提高你的作品的可发现性，我在下面列出了这些。
> 
> ## Upload checkpoints in seperate model repos, make sure download stats work
> I see the models are already on the hub which is great, however we recommend pushing checkpoints to individual model repos so that download stats work.
> 
> Here's a guide: https://huggingface.co/docs/hub/models-uploading#upload-a-pytorch-model-using-huggingfacehub. The PyTorchModelHubMixin is suited for custom PyTorch models, as is the case here.
> 
> Let me know if you need any help regarding this!
> 
> Cheers,
> 
> Niels ML Engineer @ HF 🤗

Thanks , we will add this support soon.

**Comment by NielsRogge** [comment]
Great! 

Btw, HustVL does have an organization on the hub: https://huggingface.co/hustvl

Would be great to make them available there!

**Comment by NielsRogge** [comment]
Hi @xiazhi1 I saw your email, would it be possible to contact someone part of the HustVL organization on HF and ask for access?

**Comment by NielsRogge** [comment]
HI @xiazhi1 I saw you pushed a checkpoint here: https://huggingface.co/hustvl/LKCell-L. Great!

However I also see you removed the Mixin: https://github.com/hustvl/LKCell/commit/8583e6abcf00f82ffeaf94e46cfe9c352ed1278d, any reason for this?

Let us know if there's any problem with it :)

**Comment by xiazhi1** [comment]
> HI @xiazhi1 I saw you pushed a checkpoint here: https://huggingface.co/hustvl/LKCell-L. Great!
> 
> However I also see you removed the Mixin: [8583e6a](https://github.com/hustvl/LKCell/commit/8583e6abcf00f82ffeaf94e46cfe9c352ed1278d), any reason for this?
> 
> Let us know if there's any problem with it :)

That was a wrong upload. We will upload our weights to [https://huggingface.co/hustvl](https://huggingface.co/hustvl) Please stay tuned.
