### ISSUE TITLE
Can you provide the pretrained_encoder: /data5/ziweicui/semi_supervised_resnet50-08389792.pth file from config.yaml?

### ISSUE THREAD

**Issue by happywt** [hustvl/LKCell#3]
Can you provide the pretrained_encoder: /data5/ziweicui/semi_supervised_resnet50-08389792.pth file from config.yaml?
semi_supervised_resnet50-08389792.pth and the Pre-trained UnirepLKNet models you provide in your GitHub: Is unireplkNet-models the same thing?
Your reply is very important to me, thank you.

**Comment by xiazhi1** [comment]
> Can you provide the pretrained_encoder: /data5/ziweicui/semi_supervised_resnet50-08389792.pth file from config.yaml? semi_supervised_resnet50-08389792.pth and the Pre-trained UnirepLKNet models you provide in your GitHub: Is unireplkNet-models the same thing? Your reply is very important to me, thank you.

Yes, they are the same thing. Sorry for the inaccurate description. We will speed up the process of improving it.

**Comment by ziwei-cui** [comment]
The pretrained_encoder: /data5/ziweicui/semi_supervised_resnet50-08389792.pth file from config.yaml,  is used for our ablation. So, you just need to change this path to the path including unireplkNet-models. Thanks for the reminder.
