### ISSUE TITLE
关于 depthwise-conv2d-implicit-gemm

### ISSUE THREAD

**Issue by wsw-sa** [hustvl/LKCell#5]
请问您给的链接里，只有个issue是有关这个包的，[https://github.com/AILab-CVC/UniRepLKNet/issues/18](url)，这似乎并不是解决您的包安装报错的问题的，具体报错信息如下：
ERROR: Could not find a version that satisfies the requirement depthwise-conv2d-implicit-gemm==0.0.0 (from versions: none)
ERROR: No matching distribution found for depthwise-conv2d-implicit-gemm==0.0.0
期待您的回复

**Comment by xiazhi1** [comment]
In fact, the installation method is in this section of their readme [use-an-efficient-large-kernel-convolution-with-pytorch](https://github.com/AILab-CVC/UniRepLKNet#use-an-efficient-large-kernel-convolution-with-pytorch)
